model:
  base_learning_rate: 4.5e-6
  target: taming.models.vqgan.VQModel
  params:
    ckpt_path: logs/coco_ckpt/coco_epoch117.ckpt
    ct_ckpt_dir: logs/ct_ckpt_path/clip
    embed_dim: 256
    n_embed: 8192
    monitor: val/total_loss
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      dropout: 0.0
      vocab_size: 49408
    ctconfig:                #cliptransformer_config
      context_length:  256
      vocab_size: 49408
      width: 512
      heads: 4
      layers: 10
      quick_gelu: True
      pad_id: 0
    lossconfig:
      target: taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 250001
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 6
    num_workers: 8
    train:
      target: taming.data.coco.CocoImagesAndCaptionsTrain
      params:
        size: 296
        crop_size: 256
        onehot_segmentation: true
        use_stuffthing: true
    validation:
      target: taming.data.coco.CocoImagesAndCaptionsValidation
      params:
        size: 256
        crop_size: 256
        onehot_segmentation: true
        use_stuffthing: true
